import React,{useEffect,useMemo,useState}from'react';
import{Bot,Command,ExternalLink,LayoutGrid,MessageSquare,Moon,MonitorUp,Plus,Send,Settings as SettingsIcon,Sparkles,Sun,Terminal,Wifi,X,Zap}from'lucide-react';
import{createRoot}from'react-dom/client';
import'./styles.css';
import'./mobile.css';
import'./empty.css';

type Provider={id:string;name:string;detail:string;connected:boolean};
type Message={id:string;from:'you'|'agent';text:string;at:string};
type Agent={id:string;name:string;role:string;provider:string;providerName:string;status:'ready'|'working';messages:Message[];sessionId?:string};
const storeKey='cosmic-agents-v1';
const themeKey='cosmic-theme-mode';
type ThemeMode='light'|'dark'|'auto';
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const newAgent=(provider:Provider):Agent=>({id:uid(),name:provider.name,role:'Local coding agent',provider:provider.id,providerName:provider.name,status:'ready',messages:[]});
const initialTheme=():ThemeMode=>{const saved=localStorage.getItem(themeKey);return saved==='light'||saved==='dark'||saved==='auto'?saved:'auto'};
const resolvedTheme=(mode:ThemeMode)=>mode==='auto'?(new Date().getHours()>=19||new Date().getHours()<7?'dark':'light'):mode;

function App(){
 const[agents,setAgents]=useState<Agent[]>(()=>{try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return[]}});
 const[providers,setProviders]=useState<Provider[]>([]);const[selectedId,setSelectedId]=useState<string|undefined>();
 const[connect,setConnect]=useState(false);const[session,setSession]=useState(false);const[settings,setSettings]=useState(false);const[draft,setDraft]=useState('');const[error,setError]=useState('');const[themeMode,setThemeMode]=useState<ThemeMode>(initialTheme);const[,setMinute]=useState(0);
 const agent=useMemo(()=>agents.find(item=>item.id===selectedId)||agents[0],[agents,selectedId]);
 const connected=providers.length>0;
 useEffect(()=>localStorage.setItem(storeKey,JSON.stringify(agents)),[agents]);
 useEffect(()=>{localStorage.setItem(themeKey,themeMode);const theme=resolvedTheme(themeMode);document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme},[themeMode]);
 useEffect(()=>{if(themeMode!=='auto')return;const timer=window.setInterval(()=>setMinute(value=>value+1),60000);return()=>window.clearInterval(timer)},[themeMode]);
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(data=>setProviders(data.providers||[])).catch(()=>setProviders([]))},[]);
 const createSession=(provider:Provider)=>{const item=newAgent(provider);setAgents(current=>[item,...current]);setSelectedId(item.id);setConnect(false);setSession(true);};
 const send=async()=>{
  if(!agent||!draft.trim()||agent.status==='working')return;
  const message=draft.trim(),outgoing:Message={id:uid(),from:'you',text:message,at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setDraft('');setError('');
  setAgents(current=>current.map(item=>item.id===agent.id?{...item,status:'working',messages:[...item.messages,outgoing]}:item));
  try{const response=await fetch('/api/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:agent.provider,message,sessionId:agent.sessionId})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to reach this agent.');const incoming:Message={id:uid(),from:'agent',text:data.text,at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setAgents(current=>current.map(item=>item.id===agent.id?{...item,status:'ready',sessionId:data.sessionId,messages:[...item.messages,incoming]}:item));}
  catch(cause){setAgents(current=>current.map(item=>item.id===agent.id?{...item,status:'ready'}:item));setError(cause instanceof Error?cause.message:'Unable to reach this agent.');}
 };
 return <main><aside className="rail"><div className="logo"><Sparkles size={20}/></div><nav><button className="nav active"><LayoutGrid/></button><button className="nav" onClick={()=>agent&&setSession(true)}><MessageSquare/></button><button className="nav" onClick={()=>setConnect(true)}><Bot/></button></nav><div className="rail-bottom"><button className="nav" aria-label="Open settings" onClick={()=>setSettings(true)}><SettingsIcon/></button></div></aside>
 <section className="sidebar"><div className="brand">COSMIC<span>DESKTOP</span></div><div className="workspace"><div className="ws-dot"/><div><b>Personal workspace</b><small>{agents.length} remote sessions</small></div></div><div className="side-label">COMMAND CENTER</div><button className="side-item chosen"><LayoutGrid size={17}/> Overview</button><button className="side-item" onClick={()=>agent&&setSession(true)}><MessageSquare size={17}/> Sessions</button><button className="side-item" onClick={()=>setConnect(true)}><Bot size={17}/> My agents</button><div className="side-label">CONNECTION</div><div className="connection-status"><span className={connected?'connected-dot':''}/>{connected?`${providers.length} local agents ready`:' No AI connected'}</div><div className="side-foot">Cosmic only lists local AI clients that are installed and authenticated. There is no fallback routing.</div></section>
 <section className="content"><header><div><p className="eyebrow">PRIVATE AI REMOTE DESKTOP</p><h1>{agent?'Your agents, one direct line.':'Run your AI sessions from Cosmic.'}</h1><p className="sub">Each remote session talks only to its connected AI provider.</p></div><div className="header-actions"><button className="cmd" onClick={()=>agent&&setSession(true)}><Command size={15}/>⌘ Space</button><button className="settings-trigger" aria-label="Open settings" onClick={()=>setSettings(true)}><SettingsIcon size={16}/><span>Settings</span></button><button className="invite connect-ai" onClick={()=>setConnect(true)}><Plus size={17}/> Connect AI</button></div></header>
 <div className="metrics"><Metric icon={<Zap/>} value={`${agents.filter(a=>a.status==='working').length}`} label="agents working" tint="purple"/><Metric icon={<MessageSquare/>} value={`${agents.reduce((sum,a)=>sum+a.messages.length,0)}`} label="session messages" tint="blue"/><Metric icon={<Wifi/>} value={connected?'Live':'Offline'} label="direct AI relay" tint="green"/></div>
 {!agent?<Empty onConnect={()=>setConnect(true)} connected={connected}/>:<><div className="section-title"><div><p className="eyebrow">REMOTE SESSIONS</p><h2>Active agents <span>{agents.length}</span></h2></div><button className="text-button" onClick={()=>setConnect(true)}><Plus size={14}/> Connect AI</button></div><div className="agent-list">{agents.map(item=><button key={item.id} className={'agent '+(item.id===agent.id?'selected':'')} onClick={()=>{setSelectedId(item.id);setSession(true)}}><div className="avatar">✦</div><div className="agent-info"><div><h3>{item.name}</h3><small>{item.status==='working'?'Working remotely':'Ready'}</small></div><p>{item.role} · Local {item.providerName} session</p><div className="progress"><span style={{width:item.status==='working'?'58%':'100%'}}/></div></div><ExternalLink size={15}/></button>)}</div><div className="direct-note"><MonitorUp size={17}/><div><b>Local agent routing</b><p>Your task is launched through the selected client on this computer. A client that is missing or not signed in cannot be messaged.</p></div></div></>}</section>
 {connect&&<Connect providers={providers} onClose={()=>setConnect(false)} onPick={createSession}/>}
 {settings&&<ThemeSettings mode={themeMode} onClose={()=>setSettings(false)} onChange={setThemeMode}/>}
 {session&&agent&&<Session agent={agent} draft={draft} error={error} onDraft={setDraft} onClose={()=>setSession(false)} onSend={send}/>}</main>;
}
function Metric({icon,value,label,tint}:{icon:React.ReactNode;value:string;label:string;tint:string}){return <div className={'metric '+tint}><div className="metric-icon">{icon}</div><div><b>{value}</b><span>{label}</span></div></div>}
function Empty({onConnect,connected}:{onConnect:()=>void;connected:boolean}){return <div className="empty"><div className="empty-orbit"><Sparkles size={29}/></div><p className="eyebrow">NO REMOTE SESSIONS</p><h2>Start with the AI you actually have.</h2><p>{connected?'Choose a signed-in local AI client, then send it work from one private thread.':'Sign in to a local AI client first. Cosmic will not offer agents that are unavailable on this computer.'}</p><button className="invite empty-button" onClick={onConnect}><Plus size={17}/> Connect AI</button></div>}
function Connect({providers,onClose,onPick}:{providers:Provider[];onClose:()=>void;onPick:(provider:Provider)=>void}){return <div className="overlay"><div className="palette connect"><button className="close" onClick={onClose}><X size={18}/></button><div className="palette-icon"><Bot size={21}/></div><p className="eyebrow">NEW LOCAL AGENT SESSION</p><h2>Choose a signed-in AI</h2>{providers.length?<><p className="connect-copy">Cosmic detects local clients on this computer. Selecting one sends work through that exact client and account.</p>{providers.map(provider=><button key={provider.id} className="provider" onClick={()=>onPick(provider)}><span className="provider-mark">✦</span><span><b>{provider.name}</b><small>{provider.detail}</small></span><span className="direct">Local</span></button>)}</>:<><p className="connect-copy">No authenticated local AI client is available. Sign in with the provider’s own CLI, then restart the Cosmic relay.</p><div className="relay-note"><Terminal size={15}/><code>codex login  ·  claude auth login</code></div></>}</div></div>}
function ThemeSettings({mode,onClose,onChange}:{mode:ThemeMode;onClose:()=>void;onChange:(mode:ThemeMode)=>void}){const options:[ThemeMode,string,string,React.ReactNode][]=[['light','Light','Always use the light interface.',<Sun size={19}/>],['dark','Dark','Always use the dark interface.',<Moon size={19}/>],['auto','Auto','Dark from 7 PM to 7 AM.',<SettingsIcon size={19}/>]];return <div className="overlay"><div className="palette settings-panel"><button className="close" aria-label="Close settings" onClick={onClose}><X size={18}/></button><div className="palette-icon"><SettingsIcon size={21}/></div><p className="eyebrow">PREFERENCES</p><h2>Appearance</h2><p className="connect-copy">Choose how Cosmic Desktop should look. Your choice stays on this device.</p><div className="theme-options">{options.map(([value,title,description,icon])=><button key={value} className={'theme-option '+(mode===value?'selected':'')} onClick={()=>onChange(value)}><span className="theme-icon">{icon}</span><span><b>{title}</b><small>{description}</small></span><span className="theme-check">{mode===value?'✓':''}</span></button>)}</div></div></div>}
function Session({agent,draft,error,onDraft,onClose,onSend}:{agent:Agent;draft:string;error:string;onDraft:(value:string)=>void;onClose:()=>void;onSend:()=>void}){return <div className="overlay"><div className="session-modal"><button className="close" onClick={onClose}><X size={18}/></button><div className="session-head"><div className="avatar">✦</div><div><p className="eyebrow">LOCAL SESSION · {agent.providerName.toUpperCase()}</p><h2>{agent.name}</h2><small><span className={agent.status==='working'?'working-dot':''}/>{agent.status==='working'?'Working locally…':'Client connected'}</small></div></div><div className="thread">{agent.messages.length===0?<div className="thread-empty">This session is ready. Send a task to {agent.providerName}.</div>:agent.messages.map(message=><div className={'bubble '+message.from} key={message.id}><p>{message.text}</p><time>{message.at}</time></div>)}</div>{error&&<div className="error">{error}</div>}<div className="composer"><input autoFocus value={draft} disabled={agent.status==='working'} onChange={event=>onDraft(event.target.value)} onKeyDown={event=>event.key==='Enter'&&onSend()} placeholder={`Send a task to ${agent.providerName}…`}/><button className="send" disabled={!draft.trim()||agent.status==='working'} onClick={onSend}><Send size={16}/></button></div><p className="privacy"><Wifi size={12}/> Runs through the signed-in local {agent.providerName} client</p></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
